-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkBLSX6qSJHwSgQ/z
inanGDX6psoYS/lw4QIamknZisygCgYIKoZIzj0DAQehRANCAAQUP/Otx5W08QXt
k92AEs41OVqmGPfLchc1zJtq3HfLjVPea9czqJLf/X8RS1j3uoSMejx48vDgibQw
gnYVZ4ZS
-----END PRIVATE KEY-----